### ISSUE TITLE
3. HikariCP配置踩的那些坑(以3.4.5版本为例)

### ISSUE THREAD

**Issue by nethibernate** [nethibernate/blog#17]
##### ``minimumIdle`` 和 ``maximumPoolSize``
这两个配置我的感受就是名字起的不好，让人感觉俩配置没有关系，其实它俩是相关的。用过各种池的人肯定都知道，一般池都有个特性：这个池里最少保留多少，最多放多少。Java的那个线程池 ``ThreadPoolExecutor``就是这个样子，只不过人家对应叫 ``corePoolSize``和 ``maximumPoolSize``。

简单说，这两个值就是分别用来告诉HikariCP，甭管我用不用，你最少都得放 ``minimumIdle`` 个连接在池子里；以及我如果一直要然后还不归还，最多就只能给我``maximumPoolSize``个，超过了再想要就得等着。

HikariCP早期仅支持固定大小的池子，应该是为了性能。后来被迫给分开了，但是官网依然说的清除：
> However, for maximum performance and responsiveness to spike demands, **we recommend not setting this value and instead allowing HikariCP to act as a fixed size connection pool. Default: same as maximumPoolSize**
作者的意思很明确：我迫于你们的压力，把这俩参数都提供了，但是我还是建议你们为了性能，不要配置``minimumIdle``这个值，这样HikariCP就还是个固定大小的池子（而且默认值就是``maximumPoolSize``）。言语中透漏出了种种的无奈！

如果我们配置了``minimumIdle``，则一定要配合下面这个参数``idleTimeout``才香。

##### ``idleTimeout``
其实这个参数应该和上面那俩放在一起说。当你配置了``minimumIdle`` 且它的值还和``maximumPoolSize``不同的时候，就相当于告诉HikariCP，你至少得给我创建``minimumIdle`` 多的连接备着。但是当你的系统忙的把``minimumIdle`` 个备着的连接都拿走使用时，此时再问HikariCP索要，它就得给你创建多于``minimumIdle`` 的连接，除非有连接还回来，否则我就得一直给你创建新的，直到达到上限——``maximumPoolSize``。但是，当你的系统过了忙碌期，闲下来的时候，多创建出来的那些连接，HikariCP就得抽空给干掉，因为它只需要保留``minimumIdle`` 个就好了，多了浪费。此时这个``idleTimeout``参数就有用了，它就是用来告诉HikariCP，多出来的这些连接，多长时间没再被使用，你就可以干掉了。

做个类比，和``ThreadPoolExecutor``里``keepAliveTime``用法是一样的。

这里有个问题，来自于官方文档：
>Whether a connection is retired as idle or not is subject to **a maximum variation of +30 seconds, and average variation of +15 seconds.** A connection will never be retired as idle before this timeout. 

这里提到了，干掉的时间实际上可能是``idleTimeout``+30秒，平均``idleTimeout``+15秒。这是啥意思嘞？这就要看HikariPool.java的源码了。
在HikariPool.java里，有个HouseKeeper的内部类，用来实现处理idleTimeout问题的，而这个类是定时调用的，就在HikariPool的构造函数里：
![8e74d4c31e122647e9e2efd0250b27f9.png](https://raw.githubusercontent.com/nethibernate/blog/master/photo/HikariCP%E9%85%8D%E7%BD%AE%E8%B8%A9%E7%9A%84%E9%82%A3%E4%BA%9B%E5%9D%91(%E4%BB%A53.4.5%E7%89%88%E6%9C%AC%E4%B8%BA%E4%BE%8B)/01.png)
而这里的这个间隔就是30秒：
![692b250275a80d58c452b825df15e633.png](https://raw.githubusercontent.com/nethibernate/blog/master/photo/HikariCP%E9%85%8D%E7%BD%AE%E8%B8%A9%E7%9A%84%E9%82%A3%E4%BA%9B%E5%9D%91(%E4%BB%A53.4.5%E7%89%88%E6%9C%AC%E4%B8%BA%E4%BE%8B)/02.png)
所以这个HouseKeeper每隔30秒处理一次，你某一个“多余”的连接刚好在上次检查时没过期，刚检查完就过期了，那只能在+30秒之后才能被干掉，这个+30s就是这么来的。当然从全局来看，平均就是+15秒。所以大家不用纠结这个。

另外，文档里提到的：
>A value of 0 means that idle connections are never removed from the pool. The minimum allowed value is 10000ms (10 seconds). Default: 600000 (10 minutes)

配成0，HikariCP就不干掉多于``minimumIdle``的连接了。

* * *

##### maxLifetime
好，最坑的参数上线。

首先声明，这个参数是个独立存在的，和其它的参数没有半毛钱关系，不要把它跟上面的参数以及其它time相关的参数搞混了——重要事情说三遍：没有半毛钱关系，没有半毛钱关系，没有半毛钱关系。

我先结合源码来尝试解释下这个参数是用来干什么的，然后再说为啥要有这么个参数。
HikariCP往池子里创建连接的代码只有一个地方，就是HikariPool类中的``createPoolEntry()``方法(HikariPool里放的都是一个一个的PoolEntry，而每个PoolEntry里都放了一个Connection，它俩一一对应，一个Entry对应一个Connection)：
![3d2a77ecc25687792adce061b4073f35.png](https://raw.githubusercontent.com/nethibernate/blog/master/photo/HikariCP%E9%85%8D%E7%BD%AE%E8%B8%A9%E7%9A%84%E9%82%A3%E4%BA%9B%E5%9D%91(%E4%BB%A53.4.5%E7%89%88%E6%9C%AC%E4%B8%BA%E4%BE%8B)/03.png)
红框里的就是关于``maxLifetime``最核心的代码。咱这里先不要管里面那坨子variance和time，就看红框里的，我来尝试解释下。

PoolEntry创建好之后，给这个PoolEntry设置了一个定时任务，每隔``maxLifetime``时间(代码里是lifetime这个变量)，就去尝试淘汰这个PoolEntry（就是调用``softEvictConnection``这个方法），如果淘汰成功（调用``softEvictConnection``方法返回true），则重新再往池子里添加新的连接（调用``addBagItem``方法），以补充淘汰连接空出的缺口。

我们再看一下``softEvictConnection``这个方法：
![8ad884e2982427244e67fd3e76f3996d.png](https://raw.githubusercontent.com/nethibernate/blog/master/photo/HikariCP%E9%85%8D%E7%BD%AE%E8%B8%A9%E7%9A%84%E9%82%A3%E4%BA%9B%E5%9D%91(%E4%BB%A53.4.5%E7%89%88%E6%9C%AC%E4%B8%BA%E4%BE%8B)/04.png)
首先，把当前这个PoolEntry（就是对应的Connection）标记为淘汰，然后尝试调用``connectionBag.reserve(poolEntry)``（因为owner传进来的是false），如果调用成功，则返回true，告知外面淘汰成功。

再看下``connectionBag.reserve(poolEntry)``的内部：
![890bc3b089854b6b790b6bac36119317.png](https://raw.githubusercontent.com/nethibernate/blog/master/photo/HikariCP%E9%85%8D%E7%BD%AE%E8%B8%A9%E7%9A%84%E9%82%A3%E4%BA%9B%E5%9D%91(%E4%BB%A53.4.5%E7%89%88%E6%9C%AC%E4%B8%BA%E4%BE%8B)/05.png)
就是一个CAS，尝试把没在使用中的这个PoolEntry（状态为``STATE_NOT_IN_USE``，既还在池中，没被外界获取）标记为``STATE_RESERVED``（就是不可用的意思，这个状态的PoolEntry对应的连接，不会再被外界获取到）。这里注意，这个CAS只会把没在使用中的标记为不可用，如果当前PoolEntry正在使用中，则该方法什么都不做。

总结一下上面的逻辑就是：**如果设置了``maxLifetime``，则HikariCP给池中创建的每个连接，都会定时检测，不管这个连接上一次是什么时候使用的，只要在检测时它没在使用中，就会被淘汰。** 注意，这就是``maxLifetime``参数难以被理解的原因——哪怕是一个刚用完归还的连接，不幸碰巧赶上检测了，只能说永别——使得这个参数背后的逻辑显得非常不合理。

ps：这里记录一下我一开始不理解的地方。我们使用MySQL服务器，都知道MySQL那边有一个wait_timeout参数，每个连接一旦超过这个时间没有发消息给MySQL，则MySQL服务器那边会中断该连接。这之后，如果我们的应用再使用该连接发送SQL，就会收到异常。之前自己管理MySQL连接时，会定时发送一个无用的SQL过去，以保证不会触发wait_timeout。所以最初我对于``maxLifetime``的理解就是用来干这个的，但是通过源码来看，显然``maxLifetime``不是为这个，因为如果要是用来实现这个，那至少对于刚使用完的连接不应该直接淘汰掉。另外，要是想避免触发wait_timeout，也可以定时发送SQL的方式给MySQL，而不用采用淘汰重建的方式，毕竟将还能用的连接淘汰再建立新的，这太消耗资源了，不就违背了连接池存在的初衷了么？

因此，通过在网上google之后，我在一个论坛上找到了[作者的留言](https://groups.google.com/u/1/g/hikari-cp/c/x0ObNyKsMAM)：
>The maxLifetime should be less than any infrastructure imposed timeouts, ie. stateful firewall or load-balancer timeouts.  Even if there is no "infrastructure" with timeouts between the application and the database, "infinite" connections are not recommended due to the unfortunate reality of memory/resource leaks on the database-side.  **It is better to retire connections periodically (even if only once daily) to allow the database the opportunity to clean up data structures (parse trees, query metadata caches, thread-local storage, etc.) that are associated with a session.**

作者的意思很明确，**他认为一个连接即使一直能用，也不应该一直存在下去，应该定时的关闭（哪怕一天关一次），好让数据库服务器那边清理掉一些浪费的资源。所以这才是``maxLifetime``最根本存在的原因。** 如果不理解作者设计``maxLifetime``参数的这个前提，理解起来就会非常困难。

从源码来看，我们完全可以把``maxLifetime``设置为0，从而关掉这个功能。但是紧接着的疑问就是，怎么处理wait_timeout的问题？既然``maxLifetime``不是给wait_timeout用的，那么还有别的参数处理wait_timeout问题么？答案是：没有了。如果我们关闭了``maxLifetime``，就意味着连接池中``minimumIdle``个连接永远会存在，不管你用不用。如果它们过了wait_timeout怎么办呢？答案还是在HikariPool的getConnection源码里：
![a4befd58fbda15349cd478ab26f26222.png](https://raw.githubusercontent.com/nethibernate/blog/master/photo/HikariCP%E9%85%8D%E7%BD%AE%E8%B8%A9%E7%9A%84%E9%82%A3%E4%BA%9B%E5%9D%91(%E4%BB%A53.4.5%E7%89%88%E6%9C%AC%E4%B8%BA%E4%BE%8B)/06.png)
我们的应用请求一个连接时，红框里的那个方法，会对要返回的连接做一次wait_timeout的检测，如果失败了，则关闭当前连接，重新从池里再找一个连接，直到OK或者timeout。那你肯定疑问，这么搞下去，连接池里就没连接了呀。不用急，可以看一下那个``closeConnection``方法：
![e5592b80addea62375a14850257ba964.png](https://raw.githubusercontent.com/nethibernate/blog/master/photo/HikariCP%E9%85%8D%E7%BD%AE%E8%B8%A9%E7%9A%84%E9%82%A3%E4%BA%9B%E5%9D%91(%E4%BB%A53.4.5%E7%89%88%E6%9C%AC%E4%B8%BA%E4%BE%8B)/07.png)
人家关了旧的会填新的进去的。至于那个``isConnectionAlive``方法，最核心的就是下面的逻辑：
![9495030743570520769e859a75cb7b07.png](https://raw.githubusercontent.com/nethibernate/blog/master/photo/HikariCP%E9%85%8D%E7%BD%AE%E8%B8%A9%E7%9A%84%E9%82%A3%E4%BA%9B%E5%9D%91(%E4%BB%A53.4.5%E7%89%88%E6%9C%AC%E4%B8%BA%E4%BE%8B)/08.png)
如果我们用的是JDBC4以上的版本，就会调用``connection.isValid``来检测wait_timeout；否则就会发送一个人为设置的testQuery过去。

对于``maxLifetime``，最后提一下，它的默认值是30分钟，我们上线的一个服务就采用了默认值，但是带来了一个问题：我们的服务总共连接了6个数据源，每个数据源16个连接，总共96个连接。每过30分钟，这些连接就会被淘汰一次，然后再创建16个连接，如此往复。MySQL的驱动有一个phantom引用的机制（可以参看我[之前的文章](https://github.com/nethibernate/blog/issues/16)），如果不发生full gc，这些东西不回收。我们的服务逻辑很简单，所以绝大多数的对象在eden就被回收了，运行半个月，full gc就发生过两次。而这些连接通过半个月的积攒，大概能到4万多个。之前不知道那里看过，每个socket会有一个缓冲区，收和发分别是37KB和25KB，这俩不计算在heap以及direct memory中，我们的服务半个月就能积攒2个G的使用内存无法释放。我们现在的做法就是把``maxLifetime``给关掉了。

**Comment by Mitsuizzz** [comment]
我们线上频繁请求的业务也出现了com.mysql.cj.jdbc.AbandonedConnectionCleanupThread内存泄漏，分析的很透彻，点赞

**Comment by nethibernate** [comment]
> 我们线上频繁请求的业务也出现了com.mysql.cj.jdbc.AbandonedConnectionCleanupThread内存泄漏，分析的很透彻，点赞

这篇小文章能够起到一些作用真是太好了。

**Comment by jearton** [comment]
那在PostgreSQL驱动中，会有这个问题吗？

**Comment by nethibernate** [comment]
> 那在PostgreSQL驱动中，会有这个问题吗？

这是连接池的问题，和驱动关系不是很大
