### ISSUE TITLE
1. 我的那些见不得人的事儿（反思）

### ISSUE THREAD

**Issue by nethibernate** [nethibernate/blog#6]
一天一篇，花了几天时间，把原来CSDN上自己写的、现在还觉得有丁点儿价值的都搬了过来，才发现，自己过去这么长时间，真的是毛都没干啊。

记得那会刚大学毕业参加工作的时候，当时RSS很盛行，就关注了几个大牛的blog，每天看的同时自己也下决心要不断的学习和成长，然后总结并写下来，想着将来回头一看，自己也是很牛逼的。但是今天看来，自己真的是挺傻逼的。

既然有些“忆苦思甜”了，那就回顾一下自己的工作历程吧。

毕业之后，误打误撞，到日本工作了两年，当时自己真的是空有“一腔热血”，看什么都觉得自己进步神速，就这样慢慢自己就开始飘了，总觉得自己在同龄人中已经是大牛的存在了，以至于回来后，渐渐的开始追求所谓的“理想”了。总觉得工作环境中各种不如意：同事不行，流程有问题，技术落后。天啦噜，现在想起来，自己俨然一副要改变世界的样子。要是放现在，估计我就自己支摊儿单干（创业）了。

上面自己的作死模式带来的直接问题就是：眼高手低。第二个金融项目，我除了耍耍嘴炮，什么都没有去学。记得当时把我分配到了底层核心研发组，按理说是个学习提升的绝佳机会，组里负责架构的大哥说，我们这个是长连接的服务，每台机器要支持上千的连接，我当时心想，怎么可能，每个socket连接都是阻塞的，一个连接就得单开一个线程，上千的线程，怎么能保证性能呢。结果人家大哥说，用nio啊，我瞬间就傻逼了，我艹，什么是nio，然后去google，自己当时英语还烂的一逼，什么select什么的，还没看懂。就这样我都没有意识到自己的不足，还继续眼高手低，天天觉得人家A设计的这个不好，B要求的东西不合理，C他们组能力太差，写的东西根本不行。现在我真想揪着当时的我，抽俩嘴巴子，然后大骂一顿：臭傻逼，你丫会什么呀？从业务、细节到架构，你tmd能做什么啊？就tm天天逼逼。

就这样，在那么好的一个项目里混了将近两年后，我离职了。我觉得这儿的工作、环境、技术还有人，完全配不上我的这个能力。我现在还记得离职的时候当时的老大给我说的一句话：祝你早日实现自己的理想！我艹，现在想起来真的臊得不行不行了，但是当时的我，真的是无知者无畏，嘴一撇，心里一句：等着瞧。

离开之后，我误打误撞，做起了游戏服务器的开发。当时招我的那个哥们对我说，想把我往架构师方面培养，当时把我美的一逼的。渐渐的，我开始有了压力，因为很多东西我都不会（那个时候甚至自己连多线程都不了解，就天天在那儿瞎逼逼：死锁啦）。不会，要不就学，要不就问，我呢，问又不好意思去问，总觉得自己拉不下脸来（自己可是要做架构师的人，怎么能去问别人呢），要是被人知道了我这个都不会可咋办？所以就只能自己埋头苦学（学还不好好学，有时候还要偷个懒）。现在返回来想想，走了太多的弯路，进步的也太慢，当时应该已经被同龄的人远远甩到后面了。

再后来，不知道花了多少时间，有些东西渐渐的懂了、明白了，也就逐渐发现自己傻逼的程度了。刚打算自己继续深入技术的时候，莫名其妙开始承担起管理的职责。自己对管理又一窍不通，一下子让我去管10多个人的团队，这一下又被架起来了。现在返回来想，当时主要出现了两个问题：

- 自己觉得，终于可以实现打造一个理想的团队的远景了。当时自己给团队成员拍着胸部保证，自己当年的那些理想，结果导致了，团队屁的能力还没有呢，就开始追求起那些有的没的了，这就是乌托邦。后来团队里各种问题，甚至有的人根本不念你的好，人家觉得你就是能力不行。
- 当了管理后，觉得有必要树立自己的威信，就不能承认自己有不足的地方，换句话说，就是什么都得会，导致了刚准备好的技术进步戛然而止；这也就算了，更傻逼的是，业务方面的，甚至是管理流程方面的问题，自己也得不懂装懂，生怕别人发现我有不会的地方、有弱点；而自己不会的地方却不能去和别人请教，自己被自己越架越高。

再后来，游戏开始被风口吹上天了，我也就跟着上天了：每天想着自己赶紧做一个爆款出来，一下子月流水过亿，上岸走上人生巅峰。自己的个人提高，滚一边儿去吧，等老子上了岸，还提高的屁啊。结果就是，时间长的大项目不愿意做；小项目根本都上不了线。游戏业务没有精进，技术没有提高，管理就更挨不着边儿了。

等我再次回过神来，又不知道多少时间过去了。现在的我，差不多能用**一无是处**来形容了：游戏做了这么多年，很多时候都是重复自己，深入的做不了，复杂的也做不了，技术能力没多少提高，和互联网相关的技术又有很大的脱节，更不要提什么大数据和AI了。

上大学的时候就有人提醒过我，太过眼高手低，说来可笑，当时的我根本都不知道眼高手低到底是什么意思，就被自己那傻逼的劲儿给抛到脑后了；后来，看了一个大牛的文章，说千万不要做一个团队里的万能扳手（就是什么细节都会一些，但是就是无法承担大任），当时也被自己那个傻逼劲儿给抛到了脑后。甚至自己拍着胸部和我的宝贝儿说，将来我要做中国开源界的大牛，写东西著书，让大家“顶礼膜拜”我这个“谦逊”的牛人...，我艹，我真的写不下去了，太丢人了。

真的想改，想改自己那些傻逼的毛病，所以我才在这里又开始了我的blog。我想让我自己改变掉，至少不要一无是处。我知道改变是很痛苦的，但是真正痛苦的，是对未来的那种恐慌。正是因为这份恐慌，才让我“隔三岔五”的偶尔反思自己，才又让我有了现在的行动。

不给自己灌鸡汤了，鸡汤灌多了，都能当水下火了。

**Comment by KunYi** [comment]
Hope you are a great guru now
